import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const generalSans = localFont({
	src: [
		{
			path: '../../public/fonts/GeneralSans-Medium.otf',
			style: 'normal',
		},
	],
	variable: '--font-general-sans',
	display: 'swap',
});

const alexandria = localFont({
	src: [
		{
			path: '../../public/fonts/Alexandria-SemiBold.ttf',
			style: 'normal',
		},
	],
	variable: '--font-alexandria',
	display: 'swap',
});

const clashDisplay = localFont({
	src: [
		{
			path: '../../public/fonts/ClashDisplay-Bold.otf',
			style: 'normal',
		},
	],
	variable: '--font-clash-display',
	display: 'swap',
});

const blauerNue = localFont({
	src: [
		{
			path: '../../public/fonts/Blauer-Nue-Regular.otf',
			style: 'normal',
		},
	],
	variable: '--font-blauer-nue',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${generalSans.variable} ${alexandria.variable} ${clashDisplay.variable} ${blauerNue.variable} font-sans antialiased`}>
				{children}
			</body>
		</html>
	);
}
