import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const generalSans = localFont({
  src: [
    {
      path: "../../public/fonts/GeneralSans-Regular.otf",
      style: "normal",
    },

  ],
  variable: "--font-general-sans",
  display: "swap",
});

const alexandria = localFont({
  src: [
    {
      path: "../../public/fonts/Alexandria-SemiBold.ttf",
      style: "normal",
    },
  ],
  variable: "--font-alexandria",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${alexandria.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
